# Generated by Django 4.2.4 on 2023-08-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bags',
            options={'ordering': ['-added_at'], 'verbose_name': 'Сумочка', 'verbose_name_plural': 'Сумочки'},
        ),
        migrations.AlterField(
            model_name='bags',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання'),
        ),
        migrations.AlterField(
            model_name='bags',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='bags',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Статус публікації'),
        ),
        migrations.AlterField(
            model_name='bags',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='bags',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='bags',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
    ]
